name: PR Build
on:
  pull_request:
    branches:
      - main
      
jobs:
  Buildit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'
      - name: build
        run: gcc main.cpp -o main
      - name: make folder
        run: |
             cp ./main ./Package
      - name: Upload Assembled
        uses: actions/upload-artifact@v2
        with:
          name: Assembled
          path: Package
#      - uses: actions/download-artifact@v3
#        with:
#          name: Assembled
#          path: ./


        
#      - name: set NPM auth ??
#        run: |
#          echo @cedricguillemet:https://npm.pkg.github.com/ > .npmrc
#          echo 'registry=http://npm.pkg.github.com/' >> .npmrc
#          echo '//npm.pkg.github.com/:_authToken=${secrets.GITHUB_TOKEN}' >> .npmrc
#        working-directory: ./Package
        

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./
        
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Package also available on https://npm.pkg.github.com registry. Package version is 0.0.0-${{GITHUB_SHA::7}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
#      - name: login in
#        run: npm login --scope=@cedricguillemet --registry=https://npm.pkg.github.com
#        working-directory: ./Package
        

          
#      - name: Versionning
#        run: npm version --no-git-tag-version 2.0.0
#        working-directory: ./Package
        
#      - name: Pack it
#        run: npm pack
#        working-directory: ./Package
        
#      - name: Pull request artifacts
#        uses: gavv/pull-request-artifacts@v1.0.0
#        with:
#          commit: ${{ github.event.pull_request.head.sha }}
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          artifacts: |
#            ./Package/garegex-2.0.0.tgz

#      - name: add artifact links to pull request and related issues step
#        uses: tonyhallett/artifacts-url-comments@v1.1.0
#        env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#            prefix: Here are the artifacts 
#            suffix: Have a nice day.
#            format: name
#            addTo: pullandissues