name: Publish Package
on:
  release:
    types: [published]

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${GITHUB_REF/refs\/tags\//}
          regex: '^(\d+\.)?(\d+)'

      - name: Make symlink
        run: ln -s versions/${{ steps.regex-match.outputs.match }}/version.h version.h 

      - name: Display structure of downloaded Assembled and Assembled-Windows folders
        run: ls -R

      - name: Build ELF 
        run: gcc main.cpp -o main.out

      - name: Run ELF
        run: ./main.out

  package:
    needs: [build-main]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3

