name: Publish Package
on:
  release:
    types: [published]

jobs:
  build-main064:
    runs-on: ubuntu-latest
    steps:
      - uses: CedricGuillemet/GARegex/.github/workflows/buildiosandroid@master
        with:
          react-native-version: '0.64'

  build-main065:
    runs-on: ubuntu-latest
    steps:
      - uses: CedricGuillemet/GARegex/.github/workflows/buildiosandroid@master
        with:
          react-native-version: '0.65'

  package:
    needs: [build-main064, build-main065]
    runs-on: ubuntu-latest
    steps:
      - run: everything done.
        shell: bash

