name: GARegex main branch update

on:
  repository_dispatch:
    types: [GARegex-main-update]

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${GITHUB_REF/refs\/tags\//}
          regex: '^(\d+\.)?(\d+\.)?(\*|\d+)$'

      - script: |
          ln -s version.h versions/0.64/version.h
        displayName: 'Make symlink'

  package:
    needs: [build-main]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3

      - name: Display structure of downloaded Assembled and Assembled-Windows folders
        run: ls -R